<?php
namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => 1, 'name' => 'Afghanistan', 'code' => 'af'],
            ['id' => 2, 'name' => 'Åland Islands', 'code' => 'ax'],
            ['id' => 3, 'name' => 'Albania', 'code' => 'al'],
            ['id' => 4, 'name' => 'Algeria', 'code' => 'dz'],
            ['id' => 5, 'name' => 'American Samoa', 'code' => 'as'],
            ['id' => 6, 'name' => 'Andorra', 'code' => 'ad'],
            ['id' => 7, 'name' => 'Angola', 'code' => 'ao'],
            ['id' => 8, 'name' => 'Anguilla', 'code' => 'ai'],
            ['id' => 9, 'name' => 'Antarctica', 'code' => 'aq'],
            ['id' => 10, 'name' => 'Antigua & Barbuda', 'code' => 'ag'],
            ['id' => 11, 'name' => 'Argentina', 'code' => 'ar'],
            ['id' => 12, 'name' => 'Armenia', 'code' => 'am'],
            ['id' => 13, 'name' => 'Aruba', 'code' => 'aw'],
            ['id' => 14, 'name' => 'Australia', 'code' => 'au'],
            ['id' => 15, 'name' => 'Austria', 'code' => 'at'],
            ['id' => 16, 'name' => 'Azerbaijan', 'code' => 'az'],
            ['id' => 17, 'name' => 'Bahamas', 'code' => 'bs'],
            ['id' => 18, 'name' => 'Bahrain', 'code' => 'bh'],
            ['id' => 19, 'name' => 'Bangladesh', 'code' => 'bd'],
            ['id' => 20, 'name' => 'Barbados', 'code' => 'bb'],
            ['id' => 21, 'name' => 'Belarus', 'code' => 'by'],
            ['id' => 22, 'name' => 'Belgium', 'code' => 'be'],
            ['id' => 23, 'name' => 'Belize', 'code' => 'bz'],
            ['id' => 24, 'name' => 'Benin', 'code' => 'bj'],
            ['id' => 25, 'name' => 'Bermuda', 'code' => 'bm'],
            ['id' => 26, 'name' => 'Bhutan', 'code' => 'bt'],
            ['id' => 27, 'name' => 'Bolivia', 'code' => 'bo'],
            ['id' => 28, 'name' => 'Caribbean Netherlands', 'code' => 'bq'],
            ['id' => 29, 'name' => 'Bosnia & Herzegovina', 'code' => 'ba'],
            ['id' => 30, 'name' => 'Botswana', 'code' => 'bw'],
            ['id' => 31, 'name' => 'Bouvet Island', 'code' => 'bv'],
            ['id' => 32, 'name' => 'Brazil', 'code' => 'br'],
            ['id' => 33, 'name' => 'British Indian Ocean Territory', 'code' => 'io'],
            ['id' => 34, 'name' => 'Brunei', 'code' => 'bn'],
            ['id' => 35, 'name' => 'Bulgaria', 'code' => 'bg'],
            ['id' => 36, 'name' => 'Burkina Faso', 'code' => 'bf'],
            ['id' => 37, 'name' => 'Burundi', 'code' => 'bi'],
            ['id' => 38, 'name' => 'Cambodia', 'code' => 'kh'],
            ['id' => 39, 'name' => 'Cameroon', 'code' => 'cm'],
            ['id' => 40, 'name' => 'Canada', 'code' => 'ca'],
            ['id' => 41, 'name' => 'Cape Verde', 'code' => 'cv'],
            ['id' => 42, 'name' => 'Cayman Islands', 'code' => 'ky'],
            ['id' => 43, 'name' => 'Central African Republic', 'code' => 'cf'],
            ['id' => 44, 'name' => 'Chad', 'code' => 'td'],
            ['id' => 45, 'name' => 'Chile', 'code' => 'cl'],
            ['id' => 46, 'name' => 'China', 'code' => 'cn'],
            ['id' => 47, 'name' => 'Christmas Island', 'code' => 'cx'],
            ['id' => 48, 'name' => 'Cocos (Keeling) Islands', 'code' => 'cc'],
            ['id' => 49, 'name' => 'Colombia', 'code' => 'co'],
            ['id' => 50, 'name' => 'Comoros', 'code' => 'km'],
            ['id' => 51, 'name' => 'Congo - Brazzaville', 'code' => 'cg'],
            ['id' => 52, 'name' => 'Congo - Kinshasa', 'code' => 'cd'],
            ['id' => 53, 'name' => 'Cook Islands', 'code' => 'ck'],
            ['id' => 54, 'name' => 'Costa Rica', 'code' => 'cr'],
            ['id' => 55, 'name' => 'Côte d\'Ivoire', 'code' => 'ci'],
            ['id' => 56, 'name' => 'Croatia', 'code' => 'hr'],
            ['id' => 57, 'name' => 'Cuba', 'code' => 'cu'],
            ['id' => 58, 'name' => 'Curaçao', 'code' => 'cw'],
            ['id' => 59, 'name' => 'Cyprus', 'code' => 'cy'],
            ['id' => 60, 'name' => 'Czechia', 'code' => 'cz'],
            ['id' => 61, 'name' => 'Denmark', 'code' => 'dk'],
            ['id' => 62, 'name' => 'Djibouti', 'code' => 'dj'],
            ['id' => 63, 'name' => 'Dominica', 'code' => 'dm'],
            ['id' => 64, 'name' => 'Dominican Republic', 'code' => 'do'],
            ['id' => 65, 'name' => 'Ecuador', 'code' => 'ec'],
            ['id' => 66, 'name' => 'Egypt', 'code' => 'eg'],
            ['id' => 67, 'name' => 'El Salvador', 'code' => 'sv'],
            ['id' => 68, 'name' => 'Equatorial Guinea', 'code' => 'gq'],
            ['id' => 69, 'name' => 'Eritrea', 'code' => 'er'],
            ['id' => 70, 'name' => 'Estonia', 'code' => 'ee'],
            ['id' => 71, 'name' => 'Ethiopia', 'code' => 'et'],
            ['id' => 72, 'name' => 'Falkland Islands (Islas Malvinas)', 'code' => 'fk'],
            ['id' => 73, 'name' => 'Faroe Islands', 'code' => 'fo'],
            ['id' => 74, 'name' => 'Fiji', 'code' => 'fj'],
            ['id' => 75, 'name' => 'Finland', 'code' => 'fi'],
            ['id' => 76, 'name' => 'France', 'code' => 'fr'],
            ['id' => 77, 'name' => 'French Guiana', 'code' => 'gf'],
            ['id' => 78, 'name' => 'French Polynesia', 'code' => 'pf'],
            ['id' => 79, 'name' => 'French Southern Territories', 'code' => 'tf'],
            ['id' => 80, 'name' => 'Gabon', 'code' => 'ga'],
            ['id' => 81, 'name' => 'Gambia', 'code' => 'gm'],
            ['id' => 82, 'name' => 'Georgia', 'code' => 'ge'],
            ['id' => 83, 'name' => 'Germany', 'code' => 'de'],
            ['id' => 84, 'name' => 'Ghana', 'code' => 'gh'],
            ['id' => 85, 'name' => 'Gibraltar', 'code' => 'gi'],
            ['id' => 86, 'name' => 'Greece', 'code' => 'gr'],
            ['id' => 87, 'name' => 'Greenland', 'code' => 'gl'],
            ['id' => 88, 'name' => 'Grenada', 'code' => 'gd'],
            ['id' => 89, 'name' => 'Guadeloupe', 'code' => 'gp'],
            ['id' => 90, 'name' => 'Guam', 'code' => 'gu'],
            ['id' => 91, 'name' => 'Guatemala', 'code' => 'gt'],
            ['id' => 92, 'name' => 'Guernsey', 'code' => 'gg'],
            ['id' => 93, 'name' => 'Guinea', 'code' => 'gn'],
            ['id' => 94, 'name' => 'Guinea-Bissau', 'code' => 'gw'],
            ['id' => 95, 'name' => 'Guyana', 'code' => 'gy'],
            ['id' => 96, 'name' => 'Haiti', 'code' => 'ht'],
            ['id' => 97, 'name' => 'Heard & McDonald Islands', 'code' => 'hm'],
            ['id' => 98, 'name' => 'Vatican City', 'code' => 'va'],
            ['id' => 99, 'name' => 'Honduras', 'code' => 'hn'],
            ['id' => 100, 'name' => 'Hong Kong', 'code' => 'hk'],
            ['id' => 101, 'name' => 'Hungary', 'code' => 'hu'],
            ['id' => 102, 'name' => 'Iceland', 'code' => 'is'],
            ['id' => 103, 'name' => 'India', 'code' => 'in'],
            ['id' => 104, 'name' => 'Indonesia', 'code' => 'id'],
            ['id' => 105, 'name' => 'Iran', 'code' => 'ir'],
            ['id' => 106, 'name' => 'Iraq', 'code' => 'iq'],
            ['id' => 107, 'name' => 'Ireland', 'code' => 'ie'],
            ['id' => 108, 'name' => 'Isle of Man', 'code' => 'im'],
            ['id' => 109, 'name' => 'Israel', 'code' => 'il'],
            ['id' => 110, 'name' => 'Italy', 'code' => 'it'],
            ['id' => 111, 'name' => 'Jamaica', 'code' => 'jm'],
            ['id' => 112, 'name' => 'Japan', 'code' => 'jp'],
            ['id' => 113, 'name' => 'Jersey', 'code' => 'je'],
            ['id' => 114, 'name' => 'Jordan', 'code' => 'jo'],
            ['id' => 115, 'name' => 'Kazakhstan', 'code' => 'kz'],
            ['id' => 116, 'name' => 'Kenya', 'code' => 'ke'],
            ['id' => 117, 'name' => 'Kiribati', 'code' => 'ki'],
            ['id' => 118, 'name' => 'North Korea', 'code' => 'kp'],
            ['id' => 119, 'name' => 'South Korea', 'code' => 'kr'],
            ['id' => 120, 'name' => 'Kosovo', 'code' => 'xk'],
            ['id' => 121, 'name' => 'Kuwait', 'code' => 'kw'],
            ['id' => 122, 'name' => 'Kyrgyzstan', 'code' => 'kg'],
            ['id' => 123, 'name' => 'Laos', 'code' => 'la'],
            ['id' => 124, 'name' => 'Latvia', 'code' => 'lv'],
            ['id' => 125, 'name' => 'Lebanon', 'code' => 'lb'],
            ['id' => 126, 'name' => 'Lesotho', 'code' => 'ls'],
            ['id' => 127, 'name' => 'Liberia', 'code' => 'lr'],
            ['id' => 128, 'name' => 'Libya', 'code' => 'ly'],
            ['id' => 129, 'name' => 'Liechtenstein', 'code' => 'li'],
            ['id' => 130, 'name' => 'Lithuania', 'code' => 'lt'],
            ['id' => 131, 'name' => 'Luxembourg', 'code' => 'lu'],
            ['id' => 132, 'name' => 'Macao', 'code' => 'mo'],
            ['id' => 133, 'name' => 'North Macedonia', 'code' => 'mk'],
            ['id' => 134, 'name' => 'Madagascar', 'code' => 'mg'],
            ['id' => 135, 'name' => 'Malawi', 'code' => 'mw'],
            ['id' => 136, 'name' => 'Malaysia', 'code' => 'my'],
            ['id' => 137, 'name' => 'Maldives', 'code' => 'mv'],
            ['id' => 138, 'name' => 'Mali', 'code' => 'ml'],
            ['id' => 139, 'name' => 'Malta', 'code' => 'mt'],
            ['id' => 140, 'name' => 'Marshall Islands', 'code' => 'mh'],
            ['id' => 141, 'name' => 'Martinique', 'code' => 'mq'],
            ['id' => 142, 'name' => 'Mauritania', 'code' => 'mr'],
            ['id' => 143, 'name' => 'Mauritius', 'code' => 'mu'],
            ['id' => 144, 'name' => 'Mayotte', 'code' => 'yt'],
            ['id' => 145, 'name' => 'Mexico', 'code' => 'mx'],
            ['id' => 146, 'name' => 'Micronesia', 'code' => 'fm'],
            ['id' => 147, 'name' => 'Moldova', 'code' => 'md'],
            ['id' => 148, 'name' => 'Monaco', 'code' => 'mc'],
            ['id' => 149, 'name' => 'Mongolia', 'code' => 'mn'],
            ['id' => 150, 'name' => 'Montenegro', 'code' => 'me'],
            ['id' => 151, 'name' => 'Montserrat', 'code' => 'ms'],
            ['id' => 152, 'name' => 'Morocco', 'code' => 'ma'],
            ['id' => 153, 'name' => 'Mozambique', 'code' => 'mz'],
            ['id' => 154, 'name' => 'Myanmar (Burma)', 'code' => 'mm'],
            ['id' => 155, 'name' => 'Namibia', 'code' => 'na'],
            ['id' => 156, 'name' => 'Nauru', 'code' => 'nr'],
            ['id' => 157, 'name' => 'Nepal', 'code' => 'np'],
            ['id' => 158, 'name' => 'Netherlands', 'code' => 'nl'],
            ['id' => 159, 'name' => 'New Caledonia', 'code' => 'nc'],
            ['id' => 160, 'name' => 'New Zealand', 'code' => 'nz'],
            ['id' => 161, 'name' => 'Nicaragua', 'code' => 'ni'],
            ['id' => 162, 'name' => 'Niger', 'code' => 'ne'],
            ['id' => 163, 'name' => 'Nigeria', 'code' => 'ng'],
            ['id' => 164, 'name' => 'Niue', 'code' => 'nu'],
            ['id' => 165, 'name' => 'Norfolk Island', 'code' => 'nf'],
            ['id' => 166, 'name' => 'Northern Mariana Islands', 'code' => 'mp'],
            ['id' => 167, 'name' => 'Norway', 'code' => 'no'],
            ['id' => 168, 'name' => 'Oman', 'code' => 'om'],
            ['id' => 169, 'name' => 'Pakistan', 'code' => 'pk'],
            ['id' => 170, 'name' => 'Palau', 'code' => 'pw'],
            ['id' => 171, 'name' => 'Palestine', 'code' => 'ps'],
            ['id' => 172, 'name' => 'Panama', 'code' => 'pa'],
            ['id' => 173, 'name' => 'Papua New Guinea', 'code' => 'pg'],
            ['id' => 174, 'name' => 'Paraguay', 'code' => 'py'],
            ['id' => 175, 'name' => 'Peru', 'code' => 'pe'],
            ['id' => 176, 'name' => 'Philippines', 'code' => 'ph'],
            ['id' => 177, 'name' => 'Pitcairn Islands', 'code' => 'pn'],
            ['id' => 178, 'name' => 'Poland', 'code' => 'pl'],
            ['id' => 179, 'name' => 'Portugal', 'code' => 'pt'],
            ['id' => 180, 'name' => 'Puerto Rico', 'code' => 'pr'],
            ['id' => 181, 'name' => 'Qatar', 'code' => 'qa'],
            ['id' => 182, 'name' => 'Réunion', 'code' => 're'],
            ['id' => 183, 'name' => 'Romania', 'code' => 'ro'],
            ['id' => 184, 'name' => 'Russia', 'code' => 'ru'],
            ['id' => 185, 'name' => 'Rwanda', 'code' => 'rw'],
            ['id' => 186, 'name' => 'St. Barthélemy', 'code' => 'bl'],
            ['id' => 187, 'name' => 'St. Helena', 'code' => 'sh'],
            ['id' => 188, 'name' => 'St. Kitts & Nevis', 'code' => 'kn'],
            ['id' => 189, 'name' => 'St. Lucia', 'code' => 'lc'],
            ['id' => 190, 'name' => 'St. Martin', 'code' => 'mf'],
            ['id' => 191, 'name' => 'St. Pierre & Miquelon', 'code' => 'pm'],
            ['id' => 192, 'name' => 'St. Vincent & Grenadines', 'code' => 'vc'],
            ['id' => 193, 'name' => 'Samoa', 'code' => 'ws'],
            ['id' => 194, 'name' => 'San Marino', 'code' => 'sm'],
            ['id' => 195, 'name' => 'São Tomé & Príncipe', 'code' => 'st'],
            ['id' => 196, 'name' => 'Saudi Arabia', 'code' => 'sa'],
            ['id' => 197, 'name' => 'Senegal', 'code' => 'sn'],
            ['id' => 198, 'name' => 'Serbia', 'code' => 'rs'],
            ['id' => 199, 'name' => 'Seychelles', 'code' => 'sc'],
            ['id' => 200, 'name' => 'Sierra Leone', 'code' => 'sl'],
            ['id' => 201, 'name' => 'Singapore', 'code' => 'sg'],
            ['id' => 202, 'name' => 'Sint Maarten', 'code' => 'sx'],
            ['id' => 203, 'name' => 'Slovakia', 'code' => 'sk'],
            ['id' => 204, 'name' => 'Slovenia', 'code' => 'si'],
            ['id' => 205, 'name' => 'Solomon Islands', 'code' => 'sb'],
            ['id' => 206, 'name' => 'Somalia', 'code' => 'so'],
            ['id' => 207, 'name' => 'South Africa', 'code' => 'za'],
            ['id' => 208, 'name' => 'South Georgia & South Sandwich Islands', 'code' => 'gs'],
            ['id' => 209, 'name' => 'South Sudan', 'code' => 'ss'],
            ['id' => 210, 'name' => 'Spain', 'code' => 'es'],
            ['id' => 211, 'name' => 'Sri Lanka', 'code' => 'lk'],
            ['id' => 212, 'name' => 'Sudan', 'code' => 'sd'],
            ['id' => 213, 'name' => 'Suriname', 'code' => 'sr'],
            ['id' => 214, 'name' => 'Svalbard & Jan Mayen', 'code' => 'sj'],
            ['id' => 215, 'name' => 'Eswatini', 'code' => 'sz'],
            ['id' => 216, 'name' => 'Sweden', 'code' => 'se'],
            ['id' => 217, 'name' => 'Switzerland', 'code' => 'ch'],
            ['id' => 218, 'name' => 'Syria', 'code' => 'sy'],
            ['id' => 219, 'name' => 'Taiwan', 'code' => 'tw'],
            ['id' => 220, 'name' => 'Tajikistan', 'code' => 'tj'],
            ['id' => 221, 'name' => 'Tanzania', 'code' => 'tz'],
            ['id' => 222, 'name' => 'Thailand', 'code' => 'th'],
            ['id' => 223, 'name' => 'Timor-Leste', 'code' => 'tl'],
            ['id' => 224, 'name' => 'Togo', 'code' => 'tg'],
            ['id' => 225, 'name' => 'Tokelau', 'code' => 'tk'],
            ['id' => 226, 'name' => 'Tonga', 'code' => 'to'],
            ['id' => 227, 'name' => 'Trinidad & Tobago', 'code' => 'tt'],
            ['id' => 228, 'name' => 'Tunisia', 'code' => 'tn'],
            ['id' => 229, 'name' => 'Turkey', 'code' => 'tr'],
            ['id' => 230, 'name' => 'Turkmenistan', 'code' => 'tm'],
            ['id' => 231, 'name' => 'Turks & Caicos Islands', 'code' => 'tc'],
            ['id' => 232, 'name' => 'Tuvalu', 'code' => 'tv'],
            ['id' => 233, 'name' => 'Uganda', 'code' => 'ug'],
            ['id' => 234, 'name' => 'Ukraine', 'code' => 'ua'],
            ['id' => 235, 'name' => 'United Arab Emirates', 'code' => 'ae'],
            ['id' => 236, 'name' => 'United Kingdom', 'code' => 'gb'],
            ['id' => 237, 'name' => 'United States', 'code' => 'us'],
            ['id' => 238, 'name' => 'U.S. Outlying Islands', 'code' => 'um'],
            ['id' => 239, 'name' => 'Uruguay', 'code' => 'uy'],
            ['id' => 240, 'name' => 'Uzbekistan', 'code' => 'uz'],
            ['id' => 241, 'name' => 'Vanuatu', 'code' => 'vu'],
            ['id' => 242, 'name' => 'Venezuela', 'code' => 've'],
            ['id' => 243, 'name' => 'Vietnam', 'code' => 'vn'],
            ['id' => 244, 'name' => 'British Virgin Islands', 'code' => 'vg'],
            ['id' => 245, 'name' => 'U.S. Virgin Islands', 'code' => 'vi'],
            ['id' => 246, 'name' => 'Wallis & Futuna', 'code' => 'wf'],
            ['id' => 247, 'name' => 'Western Sahara', 'code' => 'eh'],
            ['id' => 248, 'name' => 'Yemen', 'code' => 'ye'],
            ['id' => 249, 'name' => 'Zambia', 'code' => 'zm'],
            ['id' => 250, 'name' => 'Zimbabwe', 'code' => 'zw'],
        ];

        $provinces = [
            ['id' => 1, 'name' => 'Bas-Uele', 'country_id' => 52],
            ['id' => 2, 'name' => 'Equateur', 'country_id' => 52],
            ['id' => 3, 'name' => 'Haut-Katanga', 'country_id' => 52],
            ['id' => 4, 'name' => 'Haut-Lomami', 'country_id' => 52],
            ['id' => 5, 'name' => 'Haut-Uele', 'country_id' => 52],
            ['id' => 6, 'name' => 'Ituri', 'country_id' => 52],
            ['id' => 7, 'name' => 'Kasaï', 'country_id' => 52],
            ['id' => 8, 'name' => 'Kasaï-Central', 'country_id' => 52],
            ['id' => 9, 'name' => 'Kasaï-Oriental', 'country_id' => 52],
            ['id' => 10, 'name' => 'Kinshasa', 'country_id' => 52],
            ['id' => 11, 'name' => 'Kongo-Central', 'country_id' => 52],
            ['id' => 12, 'name' => 'Kwango', 'country_id' => 52],
            ['id' => 13, 'name' => 'Kwilu', 'country_id' => 52],
            ['id' => 14, 'name' => 'Lomami', 'country_id' => 52],
            ['id' => 15, 'name' => 'Lualaba', 'country_id' => 52],
            ['id' => 16, 'name' => 'Mai-ndombe', 'country_id' => 52],
            ['id' => 17, 'name' => 'Maniema', 'country_id' => 52],
            ['id' => 18, 'name' => 'Mongala', 'country_id' => 52],
            ['id' => 19, 'name' => 'Nord-Kivu', 'country_id' => 52],
            ['id' => 20, 'name' => 'Nord-Ubangi', 'country_id' => 52],
            ['id' => 21, 'name' => 'Sankuru', 'country_id' => 52],
            ['id' => 22, 'name' => 'Sud-Kivu', 'country_id' => 52],
            ['id' => 23, 'name' => 'Sud-Ubangi', 'country_id' => 52],
            ['id' => 24, 'name' => 'Tanganyika',  'country_id' => 52],
            ['id' => 25, 'name' => 'Tshopo', 'country_id' => 52],
            ['id' => 26, 'name' => 'Tsuapa', 'country_id' => 52],
        ];

        $villes = [
            ['id' => 1, 'name' => 'Kinshasa', 'province_id' => 10],
        ];

        $communes = [

            // Kinshasa (pas de districts, ville-province)
            ['id' => 1, 'name' => 'Gombe', 'ville_id' => 1],
            ['id' => 2, 'name' => 'Kintambo', 'ville_id' => 1],
            ['id' => 3, 'name' => 'Lingwala', 'ville_id' => 1],
            ['id' => 4, 'name' => 'Barumbu', 'ville_id' => 1],
            ['id' => 5, 'name' => 'Kinshasa', 'ville_id' => 1],
            ['id' => 6, 'name' => 'Kasa-Vubu', 'ville_id' => 1],
            ['id' => 7, 'name' => 'Ngiri-Ngiri', 'ville_id' => 1],
            ['id' => 8, 'name' => 'Kalamu', 'ville_id' => 1],
            ['id' => 9, 'name' => 'Bandalungwa', 'ville_id' => 1],
            ['id' => 10, 'name' => 'Makala', 'ville_id' => 1],
            ['id' => 11, 'name' => 'Bumbu', 'ville_id' => 1],
            ['id' => 12, 'name' => 'Selembao', 'ville_id' => 1],
            ['id' => 13, 'name' => 'Mont-Ngafula', 'ville_id' => 1],
            ['id' => 14, 'name' => 'Ngaliema', 'ville_id' => 1],
            ['id' => 15, 'name' => 'Limete', 'ville_id' => 1],
            ['id' => 16, 'name' => 'Matete', 'ville_id' => 1],
            ['id' => 17, 'name' => 'Lemba', 'ville_id' => 1],
            ['id' => 18, 'name' => 'Kisenso', 'ville_id' => 1],
            ['id' => 19, 'name' => 'Ngaba', 'ville_id' => 1],
            ['id' => 20, 'name' => 'Masina', 'ville_id' => 1],
            ['id' => 21, 'name' => 'Kimbanseke', 'ville_id' => 1],
            ['id' => 22, 'name' => 'Ndjili', 'ville_id' => 1],
            ['id' => 23, 'name' => 'Nsele', 'ville_id' => 1],
            ['id' => 24, 'name' => 'Maluku', 'ville_id' => 1],
        ];

        DB::table('countries')->insert($countries);
        DB::table('provinces')->insert($provinces);
        DB::table('villes')->insert($villes);
        DB::table('communes')->insert($communes);
    }
}