<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $languages = [
            ['name' => 'Afrikaans', 'native_name' => 'Afrikaans', 'code' => 'af', 'color' => 'bg-primary'],
            ['name' => 'Albanian', 'native_name' => 'shqip', 'code' => 'sq', 'color' => 'bg-warning'],
            ['name' => 'Amharic', 'native_name' => 'አማርኛ', 'code' => 'am', 'color' => 'bg-cyan'],
            ['name' => 'Arabic', 'native_name' => 'العربية', 'code' => 'ar', 'color' => 'bg-green'],
            ['name' => 'Aragonese', 'native_name' => 'aragonés', 'code' => 'an', 'color' => 'bg-black'],
            ['name' => 'Armenian', 'native_name' => 'հայերեն', 'code' => 'hy', 'color' => 'bg-teal'],
            ['name' => 'Asturian', 'native_name' => 'asturianu', 'code' => 'ast', 'color' => 'bg-success'],
            ['name' => 'Azerbaijani', 'native_name' => 'azərbaycan dili', 'code' => 'az', 'color' => 'bg-cyan'],
            ['name' => 'Basque', 'native_name' => 'euskara', 'code' => 'eu', 'color' => 'bg-indigo'],
            ['name' => 'Belarusian', 'native_name' => 'беларуская', 'code' => 'be', 'color' => 'bg-teal'],
            ['name' => 'Bengali', 'native_name' => 'বাংলা', 'code' => 'bn', 'color' => 'bg-black'],
            ['name' => 'Bosnian', 'native_name' => 'bosanski', 'code' => 'bs', 'color' => 'bg-green'],
            ['name' => 'Breton', 'native_name' => 'brezhoneg', 'code' => 'br', 'color' => 'bg-primary'],
            ['name' => 'Bulgarian', 'native_name' => 'български', 'code' => 'bg', 'color' => 'bg-warning'],
            ['name' => 'Catalan', 'native_name' => 'català', 'code' => 'ca', 'color' => 'bg-teal'],
            ['name' => 'Central Kurdish', 'native_name' => 'کوردی (دەستنوسی عەرەبی)', 'code' => 'ckb', 'color' => 'bg-black'],
            ['name' => 'Chinese', 'native_name' => '中文', 'code' => 'zh', 'color' => 'bg-green'],
            ['name' => 'Chinese (Hong Kong)', 'native_name' => '中文（香港）', 'code' => 'zh-hk', 'color' => 'bg-cyan'],
            ['name' => 'Chinese (Simplified)', 'native_name' => '中文（简体）', 'code' => 'zh-cn', 'color' => 'bg-primary'],
            ['name' => 'Chinese (Traditional)', 'native_name' => '中文（繁體）', 'code' => 'zh-tw', 'color' => 'bg-danger'],
            ['name' => 'Corsican', 'native_name' => 'Corsican', 'code' => 'co', 'color' => 'bg-cyan'],
            ['name' => 'Croatian', 'native_name' => 'hrvatski', 'code' => 'hr', 'color' => 'bg-black'],
            ['name' => 'Czech', 'native_name' => 'čeština', 'code' => 'cs', 'color' => 'bg-warning'],
            ['name' => 'Danish', 'native_name' => 'dansk', 'code' => 'da', 'color' => 'bg-primary'],
            ['name' => 'Dutch', 'native_name' => 'Nederlands', 'code' => 'nl', 'color' => 'bg-teal'],
            ['name' => 'English', 'native_name' => 'English', 'code' => 'en', 'color' => 'bg-danger'],
            ['name' => 'English (Australia)', 'native_name' => 'English (Australia)', 'code' => 'en-au', 'color' => 'bg-green'],
            ['name' => 'English (Canada)', 'native_name' => 'English (Canada)', 'code' => 'en-ca', 'color' => 'bg-black'],
            ['name' => 'English (India)', 'native_name' => 'English (India)', 'code' => 'en-in', 'color' => 'bg-cyan'],
            ['name' => 'English (New Zealand)', 'native_name' => 'English (New Zealand)', 'code' => 'en-nz', 'color' => 'bg-primary'],
            ['name' => 'English (South Africa)', 'native_name' => 'English (South Africa)', 'code' => 'en-za', 'color' => 'bg-indigo'],
            ['name' => 'English (United Kingdom)', 'native_name' => 'English (United Kingdom)', 'code' => 'en-gb', 'color' => 'bg-black'],
            ['name' => 'English (United States)', 'native_name' => 'English (United States)', 'code' => 'en-us', 'color' => 'bg-teal'],
            ['name' => 'Esperanto', 'native_name' => 'esperanto', 'code' => 'eo', 'color' => 'bg-green'],
            ['name' => 'Estonian', 'native_name' => 'eesti', 'code' => 'et', 'color' => 'bg-cyan'],
            ['name' => 'Faroese', 'native_name' => 'føroyskt', 'code' => 'fo', 'color' => 'bg-primary'],
            ['name' => 'Filipino', 'native_name' => 'Filipino', 'code' => 'fil', 'color' => 'bg-black'],
            ['name' => 'Finnish', 'native_name' => 'suomi', 'code' => 'fi', 'color' => 'bg-cyan'],
            ['name' => 'French', 'native_name' => 'français', 'code' => 'fr', 'color' => 'bg-primary'],
            ['name' => 'French (Canada)', 'native_name' => 'français (Canada)', 'code' => 'fr-ca', 'color' => 'bg-success'],
            ['name' => 'French (France)', 'native_name' => 'français (France)', 'code' => 'fr-fr', 'color' => 'bg-warning'],
            ['name' => 'French (Switzerland)', 'native_name' => 'français (Suisse)', 'code' => 'fr-ch', 'color' => 'bg-black'],
            ['name' => 'Galician', 'native_name' => 'galego', 'code' => 'gl', 'color' => 'bg-primary'],
            ['name' => 'Georgian', 'native_name' => 'ქართული', 'code' => 'ka', 'color' => 'bg-teal'],
            ['name' => 'German', 'native_name' => 'Deutsch', 'code' => 'de', 'color' => 'bg-black'],
            ['name' => 'German (Austria)', 'native_name' => 'Deutsch (Österreich)', 'code' => 'de-at', 'color' => 'bg-green'],
            ['name' => 'German (Germany)', 'native_name' => 'Deutsch (Deutschland)', 'code' => 'de-de', 'color' => 'bg-danger'],
            ['name' => 'German (Liechtenstein)', 'native_name' => 'Deutsch (Liechtenstein)', 'code' => 'de-li', 'color' => 'bg-indigo'],
            ['name' => 'German (Switzerland)', 'native_name' => 'Deutsch (Schweiz)', 'code' => 'de-ch', 'color' => 'bg-cyan'],
            ['name' => 'Greek', 'native_name' => 'Ελληνικά', 'code' => 'el', 'color' => 'bg-primary'],
            ['name' => 'Guarani', 'native_name' => 'Guarani', 'code' => 'gn', 'color' => 'bg-green'],
            ['name' => 'Gujarati', 'native_name' => 'ગુજરાતી', 'code' => 'gu', 'color' => 'bg-teal'],
            ['name' => 'Hausa', 'native_name' => 'Hausa', 'code' => 'ha', 'color' => 'bg-success'],
            ['name' => 'Hawaiian', 'native_name' => 'ʻŌlelo Hawaiʻi', 'code' => 'haw', 'color' => 'bg-primary'],
            ['name' => 'Hebrew', 'native_name' => 'עברית', 'code' => 'he', 'color' => 'bg-cyan'],
            ['name' => 'Hindi', 'native_name' => 'हिन्दी', 'code' => 'hi', 'color' => 'bg-warning'],
            ['name' => 'Hungarian', 'native_name' => 'magyar', 'code' => 'hu', 'color' => 'bg-green'],
            ['name' => 'Icelandic', 'native_name' => 'íslenska', 'code' => 'is', 'color' => 'bg-black'],
            ['name' => 'Indonesian', 'native_name' => 'Indonesia', 'code' => 'id', 'color' => 'bg-danger'],
            ['name' => 'Interlingua', 'native_name' => 'Interlingua', 'code' => 'ia', 'color' => 'bg-primary'],
            ['name' => 'Irish', 'native_name' => 'Gaeilge', 'code' => 'ga', 'color' => 'bg-green'],
            ['name' => 'Italian', 'native_name' => 'italiano', 'code' => 'it', 'color' => 'bg-success'],
            ['name' => 'Italian (Italy)', 'native_name' => 'italiano (Italia)', 'code' => 'it-it', 'color' => 'bg-cyan'],
            ['name' => 'Italian (Switzerland)', 'native_name' => 'italiano (Svizzera)', 'code' => 'it-ch', 'color' => 'bg-teal'],
            ['name' => 'Japanese', 'native_name' => '日本語', 'code' => 'ja', 'color' => 'bg-indigo'],
            ['name' => 'Kannada', 'native_name' => 'ಕನ್ನಡ', 'code' => 'kn', 'color' => 'bg-primary'],
            ['name' => 'Kazakh', 'native_name' => 'қазақ тілі', 'code' => 'kk', 'color' => 'bg-cyan'],
            ['name' => 'Khmer', 'native_name' => 'ខ្មែរ', 'code' => 'km', 'color' => 'bg-black'],
            ['name' => 'Korean', 'native_name' => '한국어', 'code' => 'ko', 'color' => 'bg-primary'],
            ['name' => 'Kurdish', 'native_name' => 'Kurdî', 'code' => 'ku', 'color' => 'bg-warning'],
            ['name' => 'Kyrgyz', 'native_name' => 'кыргызча', 'code' => 'ky', 'color' => 'bg-cyan'],
            ['name' => 'Lao', 'native_name' => 'ລາວ', 'code' => 'lo', 'color' => 'bg-danger'],
            ['name' => 'Latin', 'native_name' => 'Latin', 'code' => 'la', 'color' => 'bg-primary'],
            ['name' => 'Latvian', 'native_name' => 'latviešu', 'code' => 'lv', 'color' => 'bg-orange'],
            ['name' => 'Lingala', 'native_name' => 'lingála', 'code' => 'ln', 'color' => 'bg-green'],
            ['name' => 'Lithuanian', 'native_name' => 'lietuvių', 'code' => 'lt', 'color' => 'bg-black'],
            ['name' => 'Macedonian', 'native_name' => 'македонски', 'code' => 'mk', 'color' => 'bg-primary'],
            ['name' => 'Malay', 'native_name' => 'Bahasa Melayu', 'code' => 'ms', 'color' => 'bg-indigo'],
            ['name' => 'Malayalam', 'native_name' => 'മലയാളം', 'code' => 'ml', 'color' => 'bg-green'],
            ['name' => 'Maltese', 'native_name' => 'Malti', 'code' => 'mt', 'color' => 'bg-cyan'],
            ['name' => 'Marathi', 'native_name' => 'मराठी', 'code' => 'mr', 'color' => 'bg-teal'],
            ['name' => 'Mongolian', 'native_name' => 'монгол', 'code' => 'mn', 'color' => 'bg-primary'],
            ['name' => 'Nepali', 'native_name' => 'नेपाली', 'code' => 'ne', 'color' => 'bg-danger'],
            ['name' => 'Norwegian', 'native_name' => 'norsk', 'code' => 'no', 'color' => 'bg-green'],
            ['name' => 'Norwegian Bokmål', 'native_name' => 'norsk bokmål', 'code' => 'nb', 'color' => 'bg-warning'],
            ['name' => 'Norwegian Nynorsk', 'native_name' => 'nynorsk', 'code' => 'nn', 'color' => 'bg-primary'],
            ['name' => 'Occitan', 'native_name' => 'Occitan', 'code' => 'oc', 'color' => 'bg-success'],
            ['name' => 'Oriya', 'native_name' => 'ଓଡ଼ିଆ', 'code' => 'or', 'color' => 'bg-cyan'],
            ['name' => 'Oromo', 'native_name' => 'Oromoo', 'code' => 'om', 'color' => 'bg-black'],
            ['name' => 'Pashto', 'native_name' => 'پښتو', 'code' => 'ps', 'color' => 'bg-danger'],
            ['name' => 'Persian', 'native_name' => 'فارسی', 'code' => 'fa', 'color' => 'bg-green'],
            ['name' => 'Polish', 'native_name' => 'polski', 'code' => 'pl', 'color' => 'bg-primary'],
            ['name' => 'Portuguese', 'native_name' => 'português', 'code' => 'pt', 'color' => 'bg-teal'],
            ['name' => 'Portuguese (Brazil)', 'native_name' => 'português (Brasil)', 'code' => 'pt-br', 'color' => 'bg-danger'],
            ['name' => 'Portuguese (Portugal)', 'native_name' => 'português (Portugal)', 'code' => 'pt-pt', 'color' => 'bg-black'],
            ['name' => 'Punjabi', 'native_name' => 'ਪੰਜਾਬੀ', 'code' => 'pa', 'color' => 'bg-green'],
            ['name' => 'Quechua', 'native_name' => 'Quechua', 'code' => 'qu', 'color' => 'bg-indigo'],
            ['name' => 'Romanian', 'native_name' => 'română', 'code' => 'ro', 'color' => 'bg-success'],
            ['name' => 'Romanian (Moldova)', 'native_name' => 'română (Moldova)', 'code' => 'ro-md', 'color' => 'bg-warning'],
            ['name' => 'Romansh', 'native_name' => 'rumantsch', 'code' => 'rm', 'color' => 'bg-primary'],
            ['name' => 'Russian', 'native_name' => 'русский', 'code' => 'ru', 'color' => 'bg-danger'],
            ['name' => 'Scottish Gaelic', 'native_name' => 'Scottish Gaelic', 'code' => 'gd', 'color' => 'bg-green'],
            ['name' => 'Serbian', 'native_name' => 'српски', 'code' => 'sr', 'color' => 'bg-orange'],
            ['name' => 'Serbo-Croatian', 'native_name' => 'Serbo - Croatian', 'code' => 'sh', 'color' => 'bg-teal'],
            ['name' => 'Shona', 'native_name' => 'chiShona', 'code' => 'sn', 'color' => 'bg-primary'],
            ['name' => 'Sindhi', 'native_name' => 'Sindhi', 'code' => 'sd', 'color' => 'bg-cyan'],
            ['name' => 'Sinhala', 'native_name' => 'සිංහල', 'code' => 'si', 'color' => 'bg-black'],
            ['name' => 'Slovak', 'native_name' => 'slovenčina', 'code' => 'sk', 'color' => 'bg-warning'],
            ['name' => 'Slovenian', 'native_name' => 'slovenščina', 'code' => 'sl', 'color' => 'bg-danger'],
            ['name' => 'Somali', 'native_name' => 'Soomaali', 'code' => 'so', 'color' => 'bg-green'],
            ['name' => 'Southern Sotho', 'native_name' => 'Southern Sotho', 'code' => 'st', 'color' => 'bg-primary'],
            ['name' => 'Spanish', 'native_name' => 'español', 'code' => 'es', 'color' => 'bg-orange'],
            ['name' => 'Spanish (Argentina)', 'native_name' => 'español (Argentina)', 'code' => 'es-ar', 'color' => 'bg-indigo'],
            ['name' => 'Spanish (Latin America)', 'native_name' => 'español (Latinoamérica)', 'code' => 'es-la', 'color' => 'bg-green'],
            ['name' => 'Spanish (Mexico)', 'native_name' => 'español (México)', 'code' => 'es-mx', 'color' => 'bg-cyan'],
            ['name' => 'Spanish (Spain)', 'native_name' => 'español (España)', 'code' => 'es-es', 'color' => 'bg-black'],
            ['name' => 'Spanish (United States)', 'native_name' => 'español (Estados Unidos)', 'code' => 'es-us', 'color' => 'bg-success'],
            ['name' => 'Sundanese', 'native_name' => 'Sundanese', 'code' => 'su', 'color' => 'bg-primary'],
            ['name' => 'Swahili', 'native_name' => 'Kiswahili', 'code' => 'sw', 'color' => 'bg-teal'],
            ['name' => 'Swedish', 'native_name' => 'svenska', 'code' => 'sv', 'color' => 'bg-green'],
            ['name' => 'Tajik', 'native_name' => 'тоҷикӣ', 'code' => 'tg', 'color' => 'bg-cyan'],
            ['name' => 'Tamil', 'native_name' => 'தமிழ்', 'code' => 'ta', 'color' => 'bg-warning'],
            ['name' => 'Tatar', 'native_name' => 'Tatar', 'code' => 'tt', 'color' => 'bg-primary'],
            ['name' => 'Telugu', 'native_name' => 'తెలుగు', 'code' => 'te', 'color' => 'bg-success'],
            ['name' => 'Thai', 'native_name' => 'ไทย', 'code' => 'th', 'color' => 'bg-black'],
            ['name' => 'Tigrinya', 'native_name' => 'ትግርኛ', 'code' => 'ti', 'color' => 'bg-green'],
            ['name' => 'Tongan', 'native_name' => 'lea fakatonga', 'code' => 'to', 'color' => 'bg-teal'],
            ['name' => 'Turkish', 'native_name' => 'Türkçe', 'code' => 'tr', 'color' => 'bg-primary'],
            ['name' => 'Turkmen', 'native_name' => 'Turkmen', 'code' => 'tk', 'color' => 'bg-danger'],
            ['name' => 'Twi', 'native_name' => 'Twi', 'code' => 'tw', 'color' => 'bg-indigo'],
            ['name' => 'Ukrainian', 'native_name' => 'українська', 'code' => 'uk', 'color' => 'bg-black'],
            ['name' => 'Urdu', 'native_name' => 'اردو', 'code' => 'ur', 'color' => 'bg-green'],
            ['name' => 'Uyghur', 'native_name' => 'Uyghur', 'code' => 'ug', 'color' => 'bg-cyan'],
            ['name' => 'Uzbek', 'native_name' => "o'zbek", 'code' => 'uz', 'color' => 'bg-primary'],
            ['name' => 'Vietnamese', 'native_name' => 'Tiếng Việt', 'code' => 'vi', 'color' => 'bg-success'],
            ['name' => 'Walloon', 'native_name' => 'wa', 'code' => 'wa', 'color' => 'bg-cyan'],
            ['name' => 'Welsh', 'native_name' => 'Cymraeg', 'code' => 'cy', 'color' => 'bg-primary'],
            ['name' => 'Western Frisian', 'native_name' => 'Western Frisian', 'code' => 'fy', 'color' => 'bg-teal'],
            ['name' => 'Xhosa', 'native_name' => 'Xhosa', 'code' => 'xh', 'color' => 'bg-warning'],
            ['name' => 'Yiddish', 'native_name' => 'Yiddish', 'code' => 'yi', 'color' => 'bg-indigo'],
            ['name' => 'Yoruba', 'native_name' => 'Èdè Yorùbá', 'code' => 'yo', 'color' => 'bg-green'],
            ['name' => 'Zulu', 'native_name' => 'isiZulu', 'code' => 'zu', 'color' => 'bg-black'],
        ];

        DB::table('languages')->insert($languages);
    }
}
